rule download_bam:
    params:
        url="https://www.encodeproject.org/files/{encode_id}/@@download/{encode_id}.bam",
    threads: 1
    resources:
        mem_gb=4,
    output:
        config["encode"]["bam"],
    shell:
        "wget {params.url} -O {output}"


rule download_bed:
    params:
        url="https://www.encodeproject.org/files/{encode_id}/@@download/{encode_id}.bed.gz",
    threads: 1
    resources:
        mem_gb=4,
    output:
        bed=config["encode"]["bed"],
    shell:
        "wget -O - {params.url} | gunzip -c > {output.bed}"


rule download_fasta:
    params:
        url="ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_43/GRCh38.primary_assembly.genome.fa.gz",
    threads: 1
    resources:
        mem_gb=4,
    output:
        config["fasta"],
    shell:
        "wget -O - {params.url} | gunzip -c > {output}"


rule download_gtf:
    params:
        url="ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_43/gencode.v43.annotation.gtf.gz",
    threads: 1
    resources:
        mem_gb=4,
    output:
        config["gtf"],
    shell:
        "wget -O - {params.url} | gunzip -c > {output}"
