name: EpiOut

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest cython pytest-cov pytest-xdist 
          python -m pip install -e ".[all]"
      - name: Test with pytest
        run: |
          python -m pytest -n auto tests/ --junitxml=junit/test-results.xml --cov=epiout --cov-report=xml
      - uses: actions/upload-artifact@v2
        with:
          name: test-coverage
          path: coverage.xml

  upload-to-codecov:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: Upload to Codecov
        uses: codecov/codecov-action@v1
